const Manager = require('./lib/Manager.js')
const Engineer = require('./lib/Engineer.js')
const Intern = require('./lib/Intern.js')
const Inquirer = require('inquirer')
const fs = require('fs')
const writeFile = util.promisify(fs.writeFile)